# Generated by Django 2.2.3 on 2019-07-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190723_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('tag1', 'Kinh nghiệm học tập'), ('tag2', 'Chuyện yêu đương'), ('tag3', 'Linh tinh cá nhân')], max_length=20),
        ),
    ]
