# Generated by Django 2.2.3 on 2019-07-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('tag1', 'Kinh nghiệm học tập'), ('tag2', 'Chuyện yêu đương'), ('tag3', 'Linh tinh cá nhân')], default='tag1', max_length=20),
        ),
    ]
