# Generated by Django 2.2.3 on 2019-07-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
    ]
