# Generated by Django 2.2.3 on 2019-07-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190727_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(default='do it', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='person',
            field=models.CharField(default='duc', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='post_title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
