# Generated by Django 2.2.4 on 2019-08-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190818_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='tag',
        ),
    ]
